# Generated by Django 5.2.6 on 2025-09-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='ex_img',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='ex_img',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
