# Generated by Django 5.2.6 on 2025-09-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobbies_ex_img_portfolio_ex_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbies',
            name='ex_img',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='ex_img',
        ),
    ]
