# Generated by Django 5.2.6 on 2025-10-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_libs_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedstory',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='madlib',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='finishedstory',
            name='answers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='madlib',
            name='blanks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='madlib',
            name='story_clips',
            field=models.JSONField(default=list),
        ),
    ]
