# Generated by Django 5.2.6 on 2025-10-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_libs_app', '0002_rename_name_finishedstory_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='madlib',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
