# Generated by Django 5.2.6 on 2025-09-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0003_remove_hobbies_ex_img_remove_portfolio_ex_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_img',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_img',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
