# Generated by Django 5.2.6 on 2025-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0004_hobbies_hobby_img_portfolio_portfolio_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
                ('contact_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
