# Generated by Django 5.2.6 on 2025-09-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='hobby_description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_description',
            field=models.CharField(max_length=400),
        ),
    ]
