# Generated by Django 5.2.6 on 2025-09-27 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0006_alter_hobbies_hobby_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator(code='invalid_email', message='Email must be valid')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_message',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must be alpha characters only', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='hobby_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(max_length=100),
        ),
    ]
