# Generated by Django 5.2.6 on 2025-09-27 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0007_alter_contact_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must be alpha characters only', regex='^[a-zA-Z ]*$')]),
        ),
    ]
