# Generated by Django 5.2.6 on 2025-09-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0008_alter_contact_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolio_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolio_img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolio_name',
            new_name='name',
        ),
    ]
